# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jarvisui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1316, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QLabel(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1321, 841))
        self.frame.setText("")
        self.frame.setPixmap(QtGui.QPixmap("images/frame.jpg"))
        self.frame.setScaledContents(True)
        self.frame.setObjectName("frame")
        self.bg_jarvis = QtWidgets.QLabel(self.centralwidget)
        self.bg_jarvis.setGeometry(QtCore.QRect(560, 170, 541, 301))
        self.bg_jarvis.setStyleSheet("background-color: rgb(35, 165, 212);")
        self.bg_jarvis.setText("")
        self.bg_jarvis.setScaledContents(True)
        self.bg_jarvis.setObjectName("bg_jarvis")
        self.main_gif = QtWidgets.QLabel(self.centralwidget)
        self.main_gif.setGeometry(QtCore.QRect(90, 110, 1121, 621))
        self.main_gif.setText("")
        self.main_gif.setPixmap(QtGui.QPixmap("images/main video.gif"))
        self.main_gif.setScaledContents(True)
        self.main_gif.setObjectName("main_gif")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(220, 30, 261, 31))
        self.textBrowser.setStyleSheet("color: rgb(33, 165, 229);\n"
"font: 75 16pt \"8514oem\";\n"
"background-color:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(820, 10, 241, 31))
        self.textBrowser_2.setStyleSheet("color: rgb(33, 165, 229);\n"
"font: 75 16pt \"8514oem\";\n"
"background-color:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.start_button_png_bg = QtWidgets.QLabel(self.centralwidget)
        self.start_button_png_bg.setGeometry(QtCore.QRect(140, 540, 131, 41))
        self.start_button_png_bg.setText("")
        self.start_button_png_bg.setPixmap(QtGui.QPixmap("images/Start_button.png"))
        self.start_button_png_bg.setScaledContents(True)
        self.start_button_png_bg.setObjectName("start_button_png_bg")
        self.quit_button_png_bg = QtWidgets.QLabel(self.centralwidget)
        self.quit_button_png_bg.setGeometry(QtCore.QRect(140, 590, 131, 41))
        self.quit_button_png_bg.setText("")
        self.quit_button_png_bg.setPixmap(QtGui.QPixmap("images/Quit_button.png"))
        self.quit_button_png_bg.setScaledContents(True)
        self.quit_button_png_bg.setObjectName("quit_button_png_bg")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 537, 131, 41))
        self.pushButton.setStyleSheet("background-color:transparent;\n"
"border-radius:none;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 587, 131, 41))
        self.pushButton_2.setStyleSheet("background-color:transparent;\n"
"border-radius:none;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.jarvis_gif = QtWidgets.QLabel(self.centralwidget)
        self.jarvis_gif.setGeometry(QtCore.QRect(570, 180, 521, 281))
        self.jarvis_gif.setText("")
        self.jarvis_gif.setPixmap(QtGui.QPixmap("images/jarvis_robot.gif"))
        self.jarvis_gif.setScaledContents(True)
        self.jarvis_gif.setObjectName("jarvis_gif")
        self.intial_loadin_gif = QtWidgets.QLabel(self.centralwidget)
        self.intial_loadin_gif.setGeometry(QtCore.QRect(570, 190, 171, 41))
        self.intial_loadin_gif.setText("")
        self.intial_loadin_gif.setPixmap(QtGui.QPixmap("images/intial_loading.gif"))
        self.intial_loadin_gif.setScaledContents(True)
        self.intial_loadin_gif.setObjectName("intial_loadin_gif")
        self.frame.raise_()
        self.main_gif.raise_()
        self.bg_jarvis.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.start_button_png_bg.raise_()
        self.quit_button_png_bg.raise_()
        self.jarvis_gif.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.intial_loadin_gif.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'8514oem\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'8514oem\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
